### ISSUE TITLE
Automatically hide code

### ISSUE THREAD

**Issue by MikeBarry89** [Zhouzi/TheaterJS#30]
Hi. Rather than having a link saying "hide code", how do I have the code hidden automatically? For example, in my site http://topdrawerdesigns.ie/home-testz.html I don't want the code to appear below the writing. 

Thanks!

**Comment by Zhouzi** [comment]
Hello @MikeBarry89!

Actually this portion of the code is part of the demo but shouldn't be included otherwise. So in the following snippet:

```html
<div class="scene">
    <div><span id="vader" class="">Top Drawer</span></div>
</div>

<pre id="nodebug"><!-- pre's content --></pre>
```

You should remove the `<pre>` element and its content. I noticed you also included some of the code used for the Vader/Luke scene, if you are interested in keeping only what really matters for your case, have a look at this simplified [fiddle](http://jsfiddle.net/h340gd6q/).

**Comment by MikeBarry89** [comment]
Great! Thanks a lot for tour help! Works perfectly for me now
