### ISSUE TITLE
Typing gets stuck / pauses on Chrome iOS

### ISSUE THREAD

**Issue by thomasgrist** [Zhouzi/TheaterJS#66]
Hi there,

Firstly - thank you very much for the script. It's excellent.

I have a small issue on Chrome iOS. The typing pauses / stops just before the 6th line of text on my iPhone 7: http://thomasgrist.co.uk/portfolio2017/index8.html. This isn't a problem my desktop Chrome browser.

Any ideas how to fix?

Cheers.
Thomas.

**Comment by Zhouzi** [comment]
Thanks for your kind words Thomas 👍 

Are there any details you could share with me? Maybe some errors or a reproduction scenario? Maybe a screenshot?

I'll investigate as soon as I can grab an iPhone from a friend.

**Comment by thomasgrist** [comment]
Hi Zhouzi,

Thank you for taking the time to reply and help.

I have attached two screenshots. 

Pass - What it should look like:
![pass](https://cloud.githubusercontent.com/assets/28027790/25481164/d9b7518e-2b43-11e7-918a-870831eb8a27.PNG)

Fail - What it looks like when it's stuck:
![fail](https://cloud.githubusercontent.com/assets/28027790/25481165/d9b773da-2b43-11e7-8cb0-e82e78599738.PNG)

When the last letter of the the line is very close to the right edge of the container it gets stuck on the new line. You can see in the 'fail' image above what happens. The cursor just blinks at the beginning of a line but there is no typing.

How I achieved the pass image: by leaving the page and coming back to it. When I come back to it it's either then typing again or has done all of the typing and has finished. 

Both screenshots were both on Safari so it's not just Chrome as previously. I'm not sure that it's just on Apple devices either. It might be all mobile devices? I haven't been able to test that. Everything is fine in my desktop browsers.

**Comment by Zhouzi** [comment]
Thank you very much for the detailed explanation @thomasgrist 👍 

Is it stuck at the same point every time (right after "believe in")? Is the issue the same in portrait and landscape mode?

I suspect some css to cause it. Could you open this page and see if it's working as expected: https://run.plnkr.co/h6wOYDMlwB0kW1Rs/

I copied the theaterJS code from your site and pasted it in a plunkr without any css or other resources. That way we can isolate the code and track down the bug.

_P.S.: iOS devices don't allow running other browsers than Safari. So Chrome on iOS is using the same engine as Safari under the hood. That's why the bug is present in Safari as well as Chrome._

_Regarding mobile browsers support: I hadn't the chance to test it in Safari iOS but it's working as expected on Android. The last time I checked, it was working in all modern mobile browsers._

**Comment by thomasgrist** [comment]
Hi Zhouzi, 

Thanks for your ongoing help. 

Here's some answers:

Is it stuck at the same point every time (right after "believe in")? < yes

Is the issue the same in portrait and landscape mode? < the width of the container is different in landscape mode so it gets stuck in a different place (I think when the last letter of the the line is very close to the right edge of the container it gets stuck on the new line)

https://run.plnkr.co/h6wOYDMlwB0kW1Rs/ < I get a 'Not found' page :(

When it gets stuck and I open inspector for Safari iOS remotely it seems to trigger something and it unsticks, the typing then completes (instantly). 

Don't worry, I have now managed to set a CSS animation which changes the width of the container after a certain amount of time once it's stuck so it 'unsticks it'. Thanks again for a great script.

**Comment by Zhouzi** [comment]
Thanks, Thomas 👍 

I am glad you could figure it out. Do not hesitate to reach out again if you're facing any trouble.
